dist: xenial
language: python
python:
  - 3.7

services:
  - docker

before_install:
  - pip install -U pip
  - docker pull bash:latest

install:
  - pip install -e '.[test]' -r requirements.txt coverage codecov

script:
  - coverage erase
  - coverage run --branch --source=tunnel_rpc -m pytest
  - coverage xml -i

after_success:
  - codecov