dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

addons:
  sonarcloud:
    organization: zenoscave
    token: 
      secure: "$SONAR_TOKEN"

before_install:
  - bash ./prestart.sh

install:
  - pip install -e '.[test]' -r requirements.txt coverage codecov

script:
  - pylint tunnel_rpc tests/*.py main.py
  - flake8
  - make -C docs linkcheck
  - coverage erase
  - coverage run --branch --source=tunnel_rpc -m pytest
  - coverage report -m

after_success:
  - coverage xml -i
  - sonar-scanner
  - codecov